name: e2e Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  e2e-ios-build:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master

      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.5.app

      - name: Cache node_modules/
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-
      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox-setup

      - name: Install Node Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Cache ruby gems
        uses: actions/cache@v1
        with:
          path: ios/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install ruby gems (including Cocoapods)
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: ./ios

      - name: Cache CocoaPods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.OS }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-
      - run: bundle exec pod install --repo-update
        working-directory: ./ios

      - name: Setup env
        run: ./bin/set_ha_env_github.sh

      - run: yarn build:e2e:ios

      - uses: actions/upload-artifact@v1
        with:
          name: e2e-ios-bin
          path: ios/build/Build/Products/Release-BT-iphonesimulator/BT.app

  e2e-iphone-11:
    runs-on: macos-latest
    needs: e2e-ios-build
    timeout-minutes: 15
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app
    steps:
      - uses: actions/checkout@master
      - name: Cache node_modules/
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - name: Install Node Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - run: brew tap wix/brew

      - run: brew install applesimutils

      - run: xcrun simctl create "iPhone 11" com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-5

      - run: xcrun simctl list

      - uses: actions/download-artifact@master
        with:
          name: e2e-ios-bin
          path: ios/build/Build/Products/Release-BT-iphonesimulator/BT.app

      - run: yarn test:e2e:iphone11
